// 修仙模拟器 - 核心引擎类型定义（barrel）
// 本文件已拆分为 ./types/*.ts 按业务域分文件；此处仅做 re-export，保持 @/lib/xianxia/types 导入路径不变。

export * from './types/realm';
export * from './types/spiritual-root';
export * from './types/status';
export * from './types/item';
export * from './types/pet';
export * from './types/event';
export * from './types/combat';
export * from './types/character';
export * from './types/npc';
export * from './types/causality';
export * from './types/world-fact';
export * from './types/scheduler';
export * from './types/narrative';
export * from './types/fate';
export * from './types/sect';
export * from './types/formation';
export * from './types/alchemy-pill';
export * from './types/tribulation-ascension';
export * from './types/talisman';
export * from './types/secret-realm';
export * from './types/breakthrough';
export * from './types/auction';
export * from './types/physique';
export * from './types/npc-memory';
export * from './types/worldmap';
export * from './types/crafting';
export * from './types/ending';
export * from './types/inheritance';
