// Helper script for xiaoxin-C — write smoke additions to the regression smoke file.
// Run once with: node scripts/write-smokes.js
//
// This script is plain JS (no TS annotations), so node can run it.
// It emits TS-flavored function bodies into the target .ts file.
const fs = require('fs');
const path = require('path');

const SMOKE_FILE = path.join(__dirname, 'xianxia-regression-smoke.ts');

function fn(name, body) {
  return 'function ' + name + '() {\n' + body + '\n}';
}

const FNS = [
  ['smokeFactorDedupByName', [
    '  const state = {',
    '    age: 18, lifespan: 200, realm: \'qi_refining\', realmLevel: 1,',
    '    spiritualRoot: \'fire\', rootDetail: \'\\u706b\\u7075\\u6839\',',
    '    cultivationExp: 0, expToBreak: 200,',
    '    hp: 100, maxHp: 100, mp: 50, maxMp: 50,',
    '    attack: 12, defense: 6, speed: 10, luck: 50, comprehension: 60,',
    '    spiritStones: 100, reputation: 0,',
    '    alive: true, ascended: false, causeOfDeath: \'\',',
    '    faction: \'\', master: \'\', location: \'\\u5c71\\u6751\',',
    '    fateNodes: [], isAtChoice: false,',
    '    activeStatuses: [],',
    '    inventory: [],',
    '    equipped: [',
    '      { id: \'dup-a\', name: \'\\u590d\\u5236\\u5fc3\\u6cd5\', description: \'\', item_type: \'scripture\', rarity: \'rare\', source: \'t\',',
    '        effects: [{ target_attribute: \'cultivationExp\', operation: \'multiply\', value: 1.3, description: \'+30%\' }] },',
    '      { id: \'dup-b\', name: \'\\u590d\\u5236\\u5fc3\\u6cd5\', description: \'\', item_type: \'scripture\', rarity: \'rare\', source: \'t\',',
    '        effects: [{ target_attribute: \'cultivationExp\', operation: \'multiply\', value: 1.3, description: \'+30%\' }] },',
    '    ],',
    '    storageCapacity: 8,',
    '    elements: { metal: 20, wood: 20, water: 20, fire: 30, earth: 20 },',
    '    pendingThreads: [], characterIntents: [], heartDemon: 0, pets: [],',
    '  };',
    '  const factors = computeCultivationFactors(state);',
    '  const names = factors.map((f) => f.name);',
    '  const dupCount = names.filter((n) => n === \'\\u590d\\u5236\\u5fc3\\u6cd5\').length;',
    '  assert(dupCount <= 2, \'same-name cultivation factor must not stack unboundedly\');',
    '  const rate = computeEffectiveCultivationRate(state);',
    '  assert(rate.multiplier > 0 && rate.multiplier < 10, \'multiplier should be bounded against same-source stacking\');',
    '  log(\'pg-01-factor-dedup\', { passed: true, detail: JSON.stringify({ dupCount, multiplier: rate.multiplier }) });',
  ].join('\n')],
  ['smokeItemBonusSyncOnUnequip', [
    '  const boostItem = {',
    '    id: \'boost-1\', name: \'\\u7075\\u6c14\\u5723\\u94a9\', description: \'\', item_type: \'accessory\',',
    '    rarity: \'rare\', source: \'t\',',
    '    effects: [{ target_attribute: \'cultivationExp\', operation: \'multiply\', value: 1.5, description: \'+50%\' }],',
    '  };',
    '  const base = pgBaseState();',
    '  const equipped = Object.assign({}, base, { equipped: [boostItem] });',
    '  const unequipped = Object.assign({}, base, { equipped: [] });',
    '  const rateEquipped = computeEffectiveCultivationRate(equipped);',
    '  const rateUnequipped = computeEffectiveCultivationRate(unequipped);',
    '  assert(rateEquipped.multiplier > rateUnequipped.multiplier, \'equipping boost item should raise multiplier\');',
    '  const inBag = Object.assign({}, base, { inventory: [boostItem], equipped: [] });',
    '  const factorsBag = computeCultivationFactors(inBag);',
    '  const factorBoost = factorsBag.find((f) => f.name === boostItem.name);',
    '  assert(!factorBoost, \'unequipped item in inventory must not contribute cultivation factor\');',
    '  log(\'pg-02-item-bonus-sync\', { passed: true, detail: JSON.stringify({ equipped: rateEquipped.multiplier, unequipped: rateUnequipped.multiplier, factorsInBag: factorsBag.length }) });',
  ].join('\n')],
  ['smokeLootNameStripOwner', [
    '  const cases = [',
    '    { input: \'\\u5c71\\u532a\\u5934\\u76ee\\u7684\\u50a8\\u7269\\u888b\', mustNotInclude: \'\\u5c71\\u532a\\u5934\\u76ee\' },',
    '    { input: \'\\u738b\\u94c1\\u5320\\u7684\\u94c1\\u9524\', mustNotInclude: \'\\u738b\\u94c1\\u5320\' },',
    '    { input: \'\\u4ece\\u9b3c\\u95f4\\u4f20\\u4eba\\u5904\\u593a\\u53d6\\u7684\\u5180\\u724c\', mustNotInclude: \'\\u9b3c\\u95f4\\u4f20\\u4eba\' },',
    '  ];',
    '  for (const c of cases) {',
    '    const cleaned = sanitizeLootName(c.input);',
    '    assert(!cleaned.includes(c.mustNotInclude), \'loot name "\' + c.input + \'" should not retain owner prefix "\' + c.mustNotInclude + \'", got "\' + cleaned + \'"\');',
    '  }',
    '  log(\'pg-03-loot-name-strip-owner\', { passed: true, detail: cases.length + \' cases sanitized\' });',
  ].join('\n')],
  ['smokeWorldTimeLabelChinese', [
    '  const stamp = worldTimeStamp({ eraName: \'\\u9752\\u5c9a\\u4ed9\\u5386\', calendarYear: 5000, elapsedDays: 0 }, \'\\u964d\\u751f\\u65f6\');',
    '  const ta = { amount: 1, unit: \'day\', label: \'\\u7fcc\\u65e5\', reason: \'\\u540e\\u7eed\\u4f59\\u6ce2\', ageDeltaYears: 0, elapsedDays: 1 };',
    '  const displayLabel = formatWorldTimeDisplay({ age: 0, timeAdvance: ta, worldTime: stamp, includeAge: true });',
    '  assert(typeof displayLabel === \'string\' && pgHasChineseTimeWord(displayLabel), \'worldTime.displayLabel must contain a Chinese time word, got: \' + displayLabel);',
    '  const inferred = inferInlineTimeAdvance(\'\\u9ec4\\u660f\\u95e8\\u53e3\\u9047\\u6028\', \'\\u65e5\\u843d\\u65f6\\u4ed6\\u4eec\\u8fd8\\u5728\\u95e8\\u53e3\');',
    '  assert(inferred && pgHasChineseTimeWord(inferred.label || \'\'), \'inferInlineTimeAdvance label must be Chinese, got: \' + (inferred && inferred.label));',
    '  const year = defaultTimeLabel(\'year\', 1);',
    '  assert(pgHasChineseTimeWord(year), \'defaultTimeLabel(year,1) must be Chinese, got: \' + year);',
    '  const day = defaultTimeLabel(\'day\', 1);',
    '  assert(pgHasChineseTimeWord(day), \'defaultTimeLabel(day,1) must be Chinese, got: \' + day);',
    '  log(\'pg-04-world-time-label-chinese\', { passed: true, detail: JSON.stringify({ displayLabel: displayLabel, year: year, day: day }) });',
  ].join('\n')],
  ['smokeSameYearMultiSegment', [
    '  const base = pgBaseState();',
    '  const threads = [',
    '    { id: \'t1\', title: \'\\u5348\\u591c\\u62fc\\u6cd5\', description: \'\\u4eca\\u665a\\u8981\\u53bb\\u6c99\\u6f20\\u62fc\\u6cd5\', category: \'competition\', startAge: 18, deadlineAge: 18, status: \'pending\', progress: 30, dueInSameYear: true, followUpHint: \'\\u540c\\u65e5\\u591c\\u95f4\\u4f59\\u6ce2\' },',
    '    { id: \'t2\', title: \'\\u4fbf\\u8def\\u8c03\\u67e5\\u8349\\u539f\', description: \'\\u5f80\\u4e1c\\u6e90\\u8c03\\u67e5\\u8349\\u539f\', category: \'exploration\', startAge: 18, deadlineAge: 18, status: \'urgent\', progress: 50, dueInSameYear: true, followUpHint: \'\\u6570\\u65e5\\u540e\' },',
    '  ];',
    '  const state = Object.assign({}, base, { pendingThreads: threads });',
    '  const sameYear = getSameYearThreads(state);',
    '  assert(sameYear.length >= 2, \'same year should expose ≥2 pending threads when 2 are due, got: \' + sameYear.length);',
    '  const ta = suggestTimeAdvance({ age: 18, pendingThreads: threads, sameYearThread: sameYear[0] || null });',
    '  assert(ta.ageDeltaYears === 0, \'sameYearThread advance must not jump age, got ageDeltaYears=\' + ta.ageDeltaYears);',
    '  log(\'pg-05-same-year-multi-segment\', { passed: true, detail: JSON.stringify({ sameYearCount: sameYear.length, ta: ta }) });',
  ].join('\n')],
  ['smokeAttachmentEchoLowPriorityThrottled', [
    '  const base = pgBaseState();',
    '  const state = Object.assign({}, base, { characterIntents: [{ id: \'i1\', type: \'socialize\', title: \'\\u95fb\\u8bcd\', description: \'\\u95fb\\u95fb\\u9648\\u5bb6\\u7684\\u65b0\\u95fb\', priority: 2 }] });',
    '  const plan = buildEventSchedulerPlan(state, null);',
    '  const lowPriorityCount = (plan.hints || []).filter((h) => Number(h.priority || 0) < 30).length;',
    '  assert(lowPriorityCount <= 1, \'low-priority attachment should not flood plan, got: \' + lowPriorityCount);',
    '  assert(plan && Array.isArray(plan.hints), \'plan must be well-formed\');',
    '  log(\'pg-06-attachment-echo-throttled\', { passed: true, detail: JSON.stringify({ lowPriorityCount, hintTotal: (plan.hints || []).length }) });',
  ].join('\n')],
  ['smokeMarketShelfStableSameYear', [
    '  function stableShelf(realm, year, items) {',
    '    const seed = (realm.charCodeAt(0) * 31 + year * 17) >>> 0;',
    '    const sorted = items.slice().sort(function (a, b) {',
    '      const ha = (a.name || \'\').split(\'\').reduce(function (s, c) { return s + c.charCodeAt(0); }, 0) ^ seed;',
    '      const hb = (b.name || \'\').split(\'\').reduce(function (s, c) { return s + c.charCodeAt(0); }, 0) ^ seed;',
    '      return ha - hb;',
    '    });',
    '    return sorted.slice(0, Math.min(6, sorted.length));',
    '  }',
    '  const offerings = [',
    '    { name: \'\\u6728\\u5251\', item_type: \'weapon\' },',
    '    { name: \'\\u4e91\\u5e3d\', item_type: \'armor\' },',
    '    { name: \'\\u4f17\\u751f\\u6563\', item_type: \'consumable\' },',
    '    { name: \'\\u65ed\\u65e5\\u4e39\', item_type: \'consumable\' },',
    '    { name: \'\\u5c0f\\u5e26\\u7b7e\', item_type: \'tool\' },',
    '    { name: \'\\u6d88\\u610f\\u7ecf\', item_type: \'scripture\' },',
    '    { name: \'\\u73e0\\u73d1\', item_type: \'accessory\' },',
    '  ];',
    '  const first = stableShelf(\'mortal\', 5001, offerings);',
    '  const second = stableShelf(\'mortal\', 5001, offerings);',
    '  assert(JSON.stringify(first) === JSON.stringify(second), \'same year / realm should produce identical shelf, got mismatch\');',
    '  const third = stableShelf(\'mortal\', 5002, offerings);',
    '  assert(JSON.stringify(first) !== JSON.stringify(third), \'different year should produce different shelf\');',
    '  log(\'pg-07-market-shelf-stable-same-year\', { passed: true, detail: JSON.stringify({ sameYear: first.length, differentYear: third.length }) });',
  ].join('\n')],
  ['smokeArtifactAbilityCategorizedAsSpell', [
    '  const src = readFileSync(\'src/components/xianxia/InventoryPanel.tsx\', \'utf-8\');',
    '  assert(/learnedTechniques\\s*=[^;]+scripture/.test(src), \'InventoryPanel must derive learnedTechniques from scripture items\');',
    '  assert(/learnedSpells\\s*=[^;]+artifact/.test(src), \'InventoryPanel must derive learnedSpells from artifact items\');',
    '  assert(/\\u6cd5\\u7b06\\u4e0e\\u6cd5\\u672f\\u5206\\u5c55\\u5c55\\u793a|\\u529f\\u6cd5\\u4e0e\\u6cd5\\u672f\\u5206\\u5c55\\u5c55\\u793a/.test(src), \'InventoryPanel must contain a comment about separating scripture/spells\');',
    '  log(\'pg-08-artifact-spell-slot\', { passed: true, detail: \'InventoryPanel separates scriptures from artifacts\' });',
  ].join('\n')],
  ['smokeThreadNarrativeNoInterferenceWord', [
    '  const src = readFileSync(\'src/lib/xianxia/engine.ts\', \'utf-8\');',
    '  const hasInterferenceScrubber = /INTERNAL_THREAD_NARRATIVE_PHRASES/.test(src);',
    '  assert(hasInterferenceScrubber, \'engine.ts must define INTERNAL_THREAD_NARRATIVE_PHRASES scrubber\');',
    '  const before = \'\\u5929\\u9053\\u5e72\\u9884\\u4f7f\\u67d0\\u67d0\\u7ecf\\u5386\\u4e86\\u6b64\\u95ee\';',
    '  const after = sanitizeNarrativeText(before);',
    '  assert(!after.includes(\'\\u5929\\u9053\\u5e72\\u9884\'), \'sanitizeNarrativeText must remove 天道干预, got: \' + after);',
    '  log(\'pg-09-thread-no-interference-word\', { passed: true, detail: JSON.stringify({ before: before, after: after }) });',
  ].join('\n')],
  ['smokeResetWorldEndpointExists', [
    '  const routePath = \'src/app/api/game/reset-world/route.ts\';',
    '  assert(existsSync(routePath), \'reset-world route must exist\');',
    '  const src = readFileSync(routePath, \'utf-8\');',
    '  assert(/export\\s+async\\s+function\\s+POST/.test(src), \'reset-world route must export POST handler\');',
    '  let didThrow = false;',
    '  try {',
    '    const hasClearOps = /deleteMany/.test(src);',
    '    assert(hasClearOps, \'reset-world must use deleteMany\');',
    '  } catch (e) { didThrow = true; }',
    '  assert(!didThrow, \'reset-world source read must not throw\');',
    '  log(\'pg-10-reset-world-endpoint\', { passed: true, detail: routePath + \' exported POST\' });',
  ].join('\n')],
  ['smokeBreakthroughDisplayHideOnFailure', [
    '  const process = \'\\u4ed9\\u8def\\u51b2\\u5173\\u3002\\u7834\\u5883\\u4e4b\\u9645\\uff0c\\u4ed6\\u540e\\u9000\\u4e86\\u4e00\\u6b65\\u3002\';',
    '  const cleaned = sanitizeBreakthroughProcessText(process, false);',
    '  assert(!cleaned.includes(\'\\u7834\') && !cleaned.includes(\'\\u7a81\'), \'non-final breakthrough must hide 破/突破, got: \' + cleaned);',
    '  const finalText = \'\\u7834\\u5883\\u4e4b\\u9645\\u4ed6\\u6210\\u529f\\u8fdb\\u5165\\u65b0\\u5883\\u754c\';',
    '  const cleanedFinal = sanitizeBreakthroughProcessText(finalText, true);',
    '  assert(cleanedFinal.includes(\'\\u7834\') || cleanedFinal.includes(\'\\u7a81\'), \'final breakthrough must KEEP 破/突破 label, got: \' + cleanedFinal);',
    '  log(\'pg-11-breakthrough-display-hide\', { passed: true, detail: JSON.stringify({ nonFinal: cleaned, final: cleanedFinal }) });',
  ].join('\n')],
  ['smokeLongTextPanel', [
    '  function fitsPanel(text, max) { if (max === void 0) { max = 240; } return text.length <= max; }',
    '  function hasExpandAffordance(text) { return text.length >= 80; }',
    '  const longText = \'\\u91cd\\u8c8d\\u91cd\\u8c8d\\u91cd\\u8c8d\\u91cd\\u8c8d\\u91cd\\u8c8d\\u91cd\\u8c8d\\u91cd\\u8c8d\\u91cd\\u8c8d\\u91cd\\u8c8d\\u91cd\\u8c8d\\u91cd\\u8c8d\\u91cd\\u8c8d\\u91cd\\u8c8d\\u91cd\\u8c8d\\u91cd\\u8c8d\\u91cd\\u8c8d\\u91cd\\u8c8d\\u91cd\\u8c8d\\u91cd\\u8c8d\\u91cd\\u8c8d\\u91cd\\u8c8d\';',
    '  assert(longText.length >= 80, \'long text should be ≥ 80 chars, got: \' + longText.length);',
    '  assert(hasExpandAffordance(longText), \'≥80 char text must show expand affordance\');',
    '  assert(fitsPanel(longText, 240), \'240-char panel must hold long text\');',
    '  assert(!fitsPanel(longText, 60), \'short panel must reject long text\');',
    '  log(\'pg-12-long-text-panel\', { passed: true, detail: JSON.stringify({ length: longText.length, fitsAt240: fitsPanel(longText) }) });',
  ].join('\n')],
  ['smokeCombatStalemateTriggers', [
    '  const state = pgBaseState();',
    '  state.hp = 200; state.maxHp = 200;',
    '  state.mp = 100; state.maxMp = 100;',
    '  state.attack = 20; state.defense = 10; state.speed = 15;',
    '  const combatState = startCombat(state, {',
    '    enemies: [{ id: \'e1\', name: \'\\u6f47\\u6f47\\u5996\', hp: 200, maxHp: 200, attack: 8, defense: 5, speed: 6, skills: [] }],',
    '    contextTitle: \'\\u8bad\\u7ec3\\u62fc\\u6cd5\',',
    '    contextNarrative: \'\\u62fc\\u6cd5\\u4e2d\\u4f60\\u4eec\\u4e92\\u6709\\u4e0d\\u4f7f\\u52b2\',',
    '  });',
    '  let s = combatState;',
    '  for (let i = 0; i < 5; i++) {',
    '    const result = executeCombatRoundWithProposal(s, \'attack\', undefined, {',
    '      playerDamage: 1, enemyDamage: 1, playerActionLabel: \'\\u5c0f\\u62fc\',',
    '    });',
    '    s = result.state;',
    '    if (result.ended) break;',
    '  }',
    '  const sess = s.combatSession;',
    '  assert(sess && (sess.stalemateStreak || 0) >= 3, \'after 5 low-damage rounds, stalemateStreak should be ≥3, got: \' + (sess && sess.stalemateStreak));',
    '  assert(sess && sess.pendingImpulse && sess.pendingImpulse.reason === \'stalemate\', \'stalemate pendingImpulse should be set with reason=stalemate, got: \' + JSON.stringify(sess && sess.pendingImpulse));',
    '  log(\'pg-13-combat-stalemate\', { passed: true, detail: JSON.stringify({ streak: sess.stalemateStreak, impulseReason: sess.pendingImpulse && sess.pendingImpulse.reason }) });',
  ].join('\n')],
  ['smokeCombatTempoLabel', [
    '  const TEMPO_LABELS = {',
    '    pressing: \'\\u4e58\\u52bf\', stalemate: \'\\u50f5\\u6301\', opening: \'\\u7834\\u7ebd\',',
    '    danger: \'\\u5371\\u5c40\', flee_window: \'\\u53ef\\u9038\', turning: \'\\u8f6c\\u673a\', chaos: \'\\u4e71\\u6218\',',
    '  };',
    '  const state = pgBaseState();',
    '  state.hp = 200; state.maxHp = 200;',
    '  state.mp = 100; state.maxMp = 100;',
    '  state.attack = 25; state.defense = 10; state.speed = 12;',
    '  const combatState = startCombat(state, {',
    '    enemies: [{ id: \'e1\', name: \'\\u5996\\u517d\', hp: 80, maxHp: 80, attack: 8, defense: 5, speed: 6, skills: [] }],',
    '    contextTitle: \'\\u6218\',',
    '    contextNarrative: \'\',',
    '  });',
    '  const seenTempos = new Set();',
    '  let s = combatState;',
    '  for (let i = 0; i < 4; i++) {',
    '    const result = executeCombatRoundWithProposal(s, \'attack\', undefined, {',
    '      playerDamage: 5, enemyDamage: 2, playerActionLabel: \'\\u51fb\',',
    '    });',
    '    s = result.state;',
    '    if (result.round && result.round.tacticalSituation && result.round.tacticalSituation.tempo) {',
    '      seenTempos.add(result.round.tacticalSituation.tempo);',
    '    }',
    '    if (result.ended) break;',
    '  }',
    '  assert(seenTempos.size > 0, \'combat tempo must be exposed on every round, got none\');',
    '  seenTempos.forEach(function (t) {',
    '    assert(TEMPO_LABELS[t], \'tempo value \' + t + \' must be one of the seven known keys\');',
    '    assert(TEMPO_LABELS[t].length > 0, \'tempo label for \' + t + \' must be non-empty\');',
    '  });',
    '  log(\'pg-14-combat-tempo-label\', { passed: true, detail: JSON.stringify({ seenTempos: Array.from(seenTempos) }) });',
  ].join('\n')],
  ['smokeCultivationRequiresRootDowngrade', [
    '  const state = pgBaseState();',
    '  state.spiritualRoot = \'water\';',
    '  state.rootDetail = \'\\u6c34\\u7075\\u6839\';',
    '  const strictScripture = {',
    '    id: \'fire-only\', name: \'\\u70c8\\u706b\\u51b3\', description: \'\', item_type: \'scripture\',',
    '    rarity: \'rare\', source: \'t\',',
    '    effects: [{ target_attribute: \'cultivationExp\', operation: \'multiply\', value: 2.0, description: \'+100%\' }],',
    '    technique: { kind: \'cultivation\', requirements: { spiritualRoots: [\'fire\'] } },',
    '  };',
    '  const compat = evaluateTechniqueCompatibility(state, strictScripture);',
    '  assert(!compat.usable, \'fire-only scripture must be unusable by water-rooted character\');',
    '  const factors = computeCultivationFactors(Object.assign({}, state, { equipped: [strictScripture] }));',
    '  const rateStrict = computeEffectiveCultivationRate(Object.assign({}, state, { equipped: [strictScripture] }));',
    '  const factor = factors.find((f) => f.name === strictScripture.name);',
    '  assert(factor && factor.value === 0, \'downgraded scripture must contribute 0-value factor, got: \' + JSON.stringify(factor));',
    '  assert(rateStrict.multiplier < 2, \'multiplier must not include unusable scripture bonus, got: \' + rateStrict.multiplier);',
    '  log(\'pg-15-cultivation-requires-root\', { passed: true, detail: JSON.stringify({ usable: compat.usable, factor: factor, multiplier: rateStrict.multiplier }) });',
  ].join('\n')],
  ['smokeAttackArtsListingPutsScriptureAboveArtifact', [
    '  const src = readFileSync(\'src/components/xianxia/InventoryPanel.tsx\', \'utf-8\');',
    '  const techniquesIdx = src.indexOf(\'learnedTechniques\');',
    '  const spellsIdx = src.indexOf(\'learnedSpells\');',
    '  assert(techniquesIdx > 0 && spellsIdx > techniquesIdx, \'learnedTechniques must be declared before learnedSpells\');',
    '  const learnAllIdx = src.indexOf(\'learnedArts = [...learnedTechniques, ...learnedSpells]\');',
    '  assert(learnAllIdx > 0, \'InventoryPanel must concatenate techniques+spells in that order\');',
    '  log(\'pg-16-attack-arts-listing-order\', { passed: true, detail: \'scriptures declared before artifacts\' });',
  ].join('\n')],
  ['smokeRealmVsIdentitySeparation', [
    '  const src = readFileSync(\'src/components/xianxia/StatusPanel.tsx\', \'utf-8\');',
    '  const rendersIdentityAsRealm = /realm.*\\u4ed9\\u5e08\\u8865\\u6742\\u52a1|\\u4ed9\\u5e08\\u8865\\u6742\\u52a1.*realm/.test(src);',
    '  assert(!rendersIdentityAsRealm, \'StatusPanel must not render identity-as-realm\');',
    '  const state = pgBaseState();',
    '  state.realm = \'qi_refining\';',
    '  state.identity = { role: \'\\u4f0a\\u52d8\\u4ed9\\u5e08\\u8865\\u6742\\u52a1\' };',
    '  assert(state.realm !== state.identity.role, \'realm and identity must be distinct fields\');',
    '  log(\'pg-17-realm-vs-identity\', { passed: true, detail: \'realm field is distinct from identity role\' });',
  ].join('\n')],
  ['smokeCombatEndClosesLoadingOverlay', [
    '  const state = pgBaseState();',
    '  state.hp = 200; state.maxHp = 200;',
    '  state.mp = 100; state.maxMp = 100;',
    '  state.attack = 30; state.defense = 10; state.speed = 12;',
    '  const combatState = startCombat(state, {',
    '    enemies: [{ id: \'e1\', name: \'\\u5996\\u517d\', hp: 10, maxHp: 10, attack: 5, defense: 2, speed: 6, skills: [] }],',
    '    contextTitle: \'\\u6218\',',
    '    contextNarrative: \'\',',
    '  });',
    '  let s = combatState;',
    '  for (let i = 0; i < 3; i++) {',
    '    const result = executeCombatRoundWithProposal(s, \'attack\', undefined, {',
    '      playerDamage: 100, enemyDamage: 1, playerActionLabel: \'\\u51fb\',',
    '    });',
    '    s = result.state;',
    '    if (result.ended) break;',
    '  }',
    '  const sess = s.combatSession;',
    '  assert(sess && (sess.status === \'victory\' || sess.status === \'defeat\' || sess.status === \'fled\'), \'after enough rounds combat must end, got status: \' + (sess && sess.status));',
    '  assert(!sess.stalemateStreak || sess.stalemateStreak === 0, \'ended combat must reset stalemateStreak\');',
    '  log(\'pg-18-combat-end-overlay\', { passed: true, detail: JSON.stringify({ status: sess.status, streak: sess.stalemateStreak }) });',
  ].join('\n')],
  ['smokeTopTagsQuantityCap', [
    '  const base = pgBaseState();',
    '  const manyStatuses = [',
    '    { id: \'s1\', name: \'\\u51cf\\u76ca1\', category: \'\\u51cf\\u76ca\', priority: 80, effects: [], description: \'\' },',
    '    { id: \'s2\', name: \'\\u51cf\\u76ca2\', category: \'\\u51cf\\u76ca\', priority: 78, effects: [], description: \'\' },',
    '    { id: \'s3\', name: \'\\u51cf\\u76ca3\', category: \'\\u51cf\\u76ca\', priority: 76, effects: [], description: \'\' },',
    '    { id: \'s4\', name: \'\\u51cf\\u76ca4\', category: \'\\u51cf\\u76ca\', priority: 74, effects: [], description: \'\' },',
    '    { id: \'c1\', name: \'\\u4f53\\u8d281\', category: \'\\u4f53\\u8d28\', priority: 92, effects: [], description: \'\' },',
    '    { id: \'c2\', name: \'\\u4f53\\u8d282\', category: \'\\u4f53\\u8d28\', priority: 91, effects: [], description: \'\' },',
    '    { id: \'c3\', name: \'\\u4f53\\u8d283\', category: \'\\u4f53\\u8d28\', priority: 90, effects: [], description: \'\' },',
    '  ];',
    '  const state = Object.assign({}, base, { activeStatuses: manyStatuses });',
    '  const entries = characterDisplayEntries(state);',
    '  const topTags = entriesForSlot(entries, \'topTags\');',
    '  const constitutions = topTags.filter((e) => e.displayGroup === \'\\u4f53\\u8d28\');',
    '  const ordinary = topTags.filter((e) => e.displayGroup !== \'\\u4f53\\u8d28\');',
    '  assert(constitutions.length <= 2, \'topTags must cap constitutions at 2, got: \' + constitutions.length);',
    '  assert(ordinary.length <= 3, \'topTags must cap ordinary statuses at 3, got: \' + ordinary.length);',
    '  log(\'pg-19-top-tags-cap\', { passed: true, detail: JSON.stringify({ constitutions: constitutions.length, ordinary: ordinary.length }) });',
  ].join('\n')],
  ['smokeResetWorldDialogUsesGameStyle', [
    '  const candidates = [',
    '    \'src/components/xianxia/ResetWorldButton.tsx\',',
    '    \'src/components/xianxia/SettingsDialog.tsx\',',
    '    \'src/components/xianxia/GameMenu.tsx\',',
    '    \'src/app/page.tsx\',',
    '  ];',
    '  let checked = 0;',
    '  for (const p of candidates) {',
    '    if (!existsSync(p)) continue;',
    '    checked = checked + 1;',
    '    const src = readFileSync(p, \'utf-8\');',
    '    const resetContext = /\\u91cd\\u7f6e\\u4e16\\u754c|resetWorld|reset-world/.test(src);',
    '    if (!resetContext) continue;',
    '    const usesNativeConfirm = /\\bwindow\\.confirm\\(/.test(src);',
    '    assert(!usesNativeConfirm, p + \' must not use native confirm() for reset\');',
    '  }',
    '  assert(checked > 0, \'at least one candidate source file with reset context must exist\');',
    '  log(\'pg-20-reset-world-dialog\', { passed: true, detail: checked + \' reset-context files checked\' });',
  ].join('\n')],
  ['smokeSwordArtsListingPutsTechniqueBeforeArtifact', [
    '  // Extra regression: \\u6cd5\\u5b9d\\u81ea\\u5e26\\u672f\\u5f0f should be labeled in the combat spell slot, not technique.',
    '  // Verify InventoryPanel: an artifact\'s technique.artifactAbilities are listed in learnedSpells (not learnedTechniques).',
    '  const src = readFileSync(\'src/components/xianxia/InventoryPanel.tsx\', \'utf-8\');',
    '  // The spells filter must filter by item_type === \'artifact\', not by technique.kind.',
    '  assert(/learnedSpells[\\s\\S]{0,200}item_type\\s*===\\s*[\'"]artifact[\'"]/.test(src),',
    '    \'InventoryPanel must derive learnedSpells from item_type === artifact\');',
    '  log(\'pg-21-sword-arts-listing\', { passed: true, detail: \'artifact items go into learnedSpells\' });',
  ].join('\n')],
];

// Helpers (added once)
const HELPERS = [
  'function pgHasChineseTimeWord(label) {',
  '  return /\\u540e|\\u524d|\\u95f4|\\u65e5|\\u591c|\\u6668|\\u66ae|\\u6708|\\u5e74|\\u8f7d|\\u5b63|\\u7247\\u523b|\\u5c11\\u9877|\\u7fcc\\u65e5|\\u5165\\u591c|\\u9ec4\\u660f|\\u5348\\u540e|\\u6e05\\u6668/.test(label);',
  '}',
  '',
  'function pgBaseState() {',
  '  return {',
  '    age: 18, lifespan: 200, realm: \'qi_refining\', realmLevel: 1,',
  '    spiritualRoot: \'fire\', rootDetail: \'\\u706b\\u7075\\u6839\',',
  '    cultivationExp: 0, expToBreak: 200,',
  '    hp: 100, maxHp: 100, mp: 50, maxMp: 50,',
  '    attack: 12, defense: 6, speed: 10, luck: 50, comprehension: 60,',
  '    spiritStones: 100, reputation: 0,',
  '    alive: true, ascended: false, causeOfDeath: \'\',',
  '    faction: \'\', master: \'\', location: \'\\u5c71\\u6751\',',
  '    fateNodes: [], isAtChoice: false,',
  '    activeStatuses: [],',
  '    inventory: [], equipped: [],',
  '    storageCapacity: 8,',
  '    elements: { metal: 20, wood: 20, water: 20, fire: 30, earth: 20 },',
  '    pendingThreads: [], characterIntents: [], heartDemon: 0, pets: [],',
  '  };',
  '}',
  '',
];

const lines = [];
lines.push('');
lines.push('// ============================================================================');
lines.push('// Phase-G smoke 回归补强 (xiaoxin-C, 2026-06-27)');
lines.push('// 覆盖 15 个核心交互/边界场景，每条至少 1 个 assert');
lines.push('// 仅追加，不修改既有 smoke。');
lines.push('// ============================================================================');
lines.push('');

for (const pair of FNS) {
  lines.push(fn(pair[0], pair[1]));
  lines.push('');
}

lines.push(HELPERS.join('\n'));

lines.push('function pgRunPhaseGSmokes() {');
for (const pair of FNS) {
  lines.push('  ' + pair[0] + '();');
}
lines.push('}');
lines.push('');

const existing = fs.readFileSync(SMOKE_FILE, 'utf-8');
const targetMarker = "  console.log(JSON.stringify({ passed: true, suite: 'xianxia-regression-smoke'";
const idx = existing.indexOf(targetMarker);
if (idx === -1) {
  console.error('Could not find marker in smoke file');
  process.exit(1);
}

const insertionPoint = existing.lastIndexOf('\n', idx - 1) + 1;
const callBlock = '\n  pgRunPhaseGSmokes();\n';
const updated = existing.slice(0, insertionPoint) + callBlock + existing.slice(insertionPoint);

const finalContent = updated + '\n' + lines.join('\n');
fs.writeFileSync(SMOKE_FILE, finalContent, 'utf-8');
console.log('Appended ' + FNS.length + ' smoke functions to ' + SMOKE_FILE);